const projects = [
  // Paste your 6 projects here
  {
    title: "StayGrid",
    description: "A full-stack property rental platform built with the MEN stack, featuring AI-powered natural language search and automatic listing description generation using the Google Gemini API. Includes category-based filtering across 11 property types, location/price search, and an 'Update Description with AI' tool for hosts.",
    image_url: "/images/staygrid.png",
    tech_stack: ["Node.js", "Express.js", "MongoDB", "EJS", "Google Gemini API", "Bootstrap"],
    github_url: "https://github.com/Sana9058/staygrid",
    live_url: "https://staygrid.onrender.com",
    featured: true,
    display_order: 1,
  },
  {
    title: "Smart Mentor",
    description: "A full-stack student-teacher appointment booking platform designed to simplify academic scheduling. Features secure Firebase Authentication, role-based access, real-time appointment management using Firestore, responsive user interface, and an intuitive dashboard for students and teachers.",
    image_url: "/images/smart-mentor.png",
    tech_stack: ["Firebase", "Firestore", "JavaScript", "HTML", "CSS"],
    github_url: "https://github.com/Sana9058/Smart-Mentor-Project",
    live_url: "https://smart-mentor-project.web.app/",
    featured: true,
    display_order: 2,
  },
  {
    title: "100 Days of LeetCode (Java)",
    description: "A structured repository containing Java solutions for LeetCode problems with optimized approaches, explanations, and continuous daily problem-solving practice.",
    image_url: "/images/dsa.png",
    tech_stack: ["Java", "DSA", "LeetCode", "Git", "GitHub"],
    github_url: "https://github.com/Sana9058/java-dsa-leetcode",
    live_url: null,
    featured: true,
    display_order: 3,
  },
  {
    title: "Expense Tracker", 
    description: "A responsive expense tracking web application for managing income and expenses with dynamic calculations and an intuitive dashboard.",
    image_url: "/images/expense-tracker.png",
    tech_stack: ["HTML", "CSS", "JavaScript"],
    github_url: "https://github.com/Sana9058/Expense-Tracker",
    live_url: "https://expense-tracker-2adbf.web.app/",
    featured: false,
    display_order: 4,
  },
  {
    title: "SkyCast Weather App",
    description: "A weather forecasting application providing real-time weather information through API integration with a clean and responsive user interface.",
    image_url: "/images/skycast.png",
    tech_stack: ["HTML", "CSS", "JavaScript", "Weather API"],
    github_url: "https://github.com/Sana9058/Skycast",
    live_url: "https://weather-app-fbedf.web.app/",
    featured: false,
    display_order: 5,
  },
  {
    title: "Simon Says Game",
    description: "A browser-based memory game built with JavaScript featuring interactive gameplay, animations, increasing difficulty, and score tracking.",
    image_url: "/images/simon-says.png",
    tech_stack: ["HTML", "CSS", "JavaScript"],
    github_url: "https://github.com/Sana9058/Simon-Says-Game",
    live_url: "https://github.com/Sana9058/Simon-Says-Game",
    featured: false,
    display_order: 6,
  },
];

module.exports = projects;